# Generated by Django 4.2.7 on 2023-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kayzpropel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
