# Generated by Django 4.2.7 on 2023-11-24 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kayzpropel', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
