# Generated by Django 4.2.7 on 2023-11-29 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kayzpropel', '0003_property_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('receipt_number', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
