# Generated by Django 4.2.7 on 2023-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kayzpropel', '0004_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='receipt_number',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
